{{ if .Values.bsf.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: open5gs-bsf
  labels:
    epc-mode: bsf
spec:
  selector:
    epc-mode: bsf
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---    
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: open5gs-bsf-d
  labels:
    epc-mode: bsf
    part-of-mesh: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      epc-mode: bsf
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "true"
      labels:
        epc-mode: bsf
        part-of-mesh: "true"
    spec:  
      containers:
        - name: bsf
          image: "{{ .Values.open5gcore.image.repository }}:{{ .Values.open5gcore.image.tag }}"
          imagePullPolicy: {{ .Values.open5gcore.image.pullPolicy }}
          securityContext:
            privileged: true
          command: ["open5gs-bsfd", "-d", "-c", "/open5gs/config-map/bsf.yaml"]
          volumeMounts:
            - name: open5gs-bsf-config
              mountPath: /open5gs/config-map/bsf.yaml
              subPath: "bsf.yaml"
      volumes:
        - name: open5gs-bsf-config
          configMap:
            name: open5gs-bsf-config

{{ end }}